# Generated by Django 4.2.8 on 2026-01-17 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scrape_type', models.CharField(choices=[('bulk', 'Bulk Scraping'), ('realtime', 'Real-time Scraping')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_portal', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('jobs_scraped', models.IntegerField(default=0)),
                ('jobs_stored', models.IntegerField(default=0)),
                ('ai_ml_jobs_found', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('request_params', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'scraping_metadata',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='scraping_me_status_d8f651_idx'), models.Index(fields=['source_portal', 'scrape_type'], name='scraping_me_source__557a18_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('job_url', models.URLField(max_length=1000)),
                ('source_portal', models.CharField(choices=[('guru', 'Guru.com'), ('truelancer', 'Truelancer.com'), ('twine', 'Twine.com'), ('remotework', 'RemoteWork.com')], max_length=20)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('skills_required', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('job_posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_ai_ml_job', models.BooleanField(db_index=True, default=False)),
                ('ai_ml_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-job_posted_at'],
                'indexes': [models.Index(fields=['is_ai_ml_job', 'status'], name='jobs_is_ai_m_ee545d_idx'), models.Index(fields=['source_portal', 'created_at'], name='jobs_source__debd05_idx'), models.Index(fields=['company', 'created_at'], name='jobs_company_d1aed4_idx')],
            },
        ),
    ]
