# Generated by Django 4.2.8 on 2026-01-17 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('company_size', models.CharField(choices=[('startup', 'Startup'), ('small', 'Small (1-50)'), ('medium', 'Medium (51-200)'), ('large', 'Large (201-1000)'), ('enterprise', 'Enterprise (1000+)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('headquarters_location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('focus_areas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='companies_name_c7a1b3_idx'), models.Index(fields=['country'], name='companies_country_19ae1c_idx'), models.Index(fields=['created_at'], name='companies_created_c84a3d_idx')],
            },
        ),
    ]
